[tools]
go = "latest"
node = "latest"
ruby = "latest"
jq = "latest"
terraform = "latest"
python = "latest"
lua = "latest"
npm = "latest"
uv = "latest"
gh = "latest"
java = "25"
cocoapods = "latest"
# gcloud = "latest"
awscli = { version = "latest", symlink_bins = "true" }
rust = "latest"
bun = "latest"
kubectl = "latest"
ktlint = "latest"
neovim = "latest"
peco = "latest"
glow = "latest"
ripgrep = "latest"
fastfetch = "latest"
act = "latest"
zellij = "latest"
bat = "latest"
delta = "latest"
lsd = "latest"
task = "latest"
fzf = "latest"
lazygit = "latest"
duf = "latest"
pre-commit = "latest"
git-lfs = "latest"
mint = "latest"
gradle = "latest"
# cargo = "latest"
dotnet = "latest"
deck = "latest"
ffmpeg = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby"]
